name: increment maven project pipelien

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin' 
      
      - name: Increment version
        run: |
          chmod +x ./scripts/increment_version.sh  # Ensure it's executable
          ./scripts/increment_version.sh  # Execute the script
        id: increment_version

      - name: Verify new_version output
        run: echo "New version is $new_version"
        env:
            new_version: ${{ env.new_version }}

      - name: Compile the code with Maven
        working-directory: ./myapp 
        run: mvn clean install

      - name: Package the JAR file
        working-directory: ./myapp 
        run: mvn package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: maven-my-app-artifact
          path: myapp/target/*.jar  

      - name: Build Docker image
        run: |
          DOCKER_IMAGE="maven-my-app:${{ env.new_version }}"
          docker build -t $DOCKER_IMAGE .

      - name: Debug Docker image tag
        run: |
          echo "DOCKER_IMAGE=$DOCKER_IMAGE"
          echo "Target tag: ${{ secrets.DOCKER_USERNAME }}/maven-my-app:${{ env.new_version }}"

      - name: Tag Docker image
        run: |
          docker tag $DOCKER_IMAGE ${{ secrets.DOCKER_USERNAME }}/maven-my-app:${{env.new_version}}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_TOKEN }}    


      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/maven-my-app:${{env.new_version}}


      - name: Run Docker image
        run: |
          docker run -d --name my-app-container ${{ secrets.DOCKER_USERNAME }}/maven-my-app:${{env.new_version}}

    
        